### ISSUE TITLE
Webserver Sample outputs broken

### ISSUE THREAD

**Issue by husamia** [jianlin-cheng/DeepComplex#3]
The sample outputs from the webserver are broken due to file not found error. 

https://github.com/jianlin-cheng/DeepComplex#sample-outputs

**Comment by farhanquadir** [comment]
Can you please give us the output link so we may investigate this further?

**Comment by husamia** [comment]
both of those links give error in the embedded viewer that file is wrong format or can not be found: 

Sample outputs are available for both homodimers and heterodimers. Homodimers 
[http://tulip.rnet.missouri.edu/deepcomplex/dimer_status_homo.php?target_name=LCI1&method=multicom&domain_class=full_length] 

Heterodimers: [http://tulip.rnet.missouri.edu/deepcomplex/dimer_status_hetero.php?target_name=SMM7_SBE3&method=multicom&domain_class=full_length]

**Comment by farhanquadir** [comment]
Thank you for letting us know about the broken links. The links has been fixed
Please look at the following links:
Heterodimers:
http://tulip.rnet.missouri.edu/deepcomplex/dimer_status_hetero_chlam.php?target_name=SMM7_SBE3&method=multicom&domain_class=full_length
Homodimers:
http://tulip.rnet.missouri.edu/deepcomplex/dimer_status_homo_chlam.php?target_name=LCI1&method=multicom&domain_class=full_length
