### ISSUE TITLE
getting the raw contact map from the server

### ISSUE THREAD

**Issue by DavidSriker** [jianlin-cheng/DeepComplex#4]
Hi

I was wondering is it possible to download the raw contact map prediction (either top-L or any of the other alternatives) when sending a job to the server?
I sent a job and I want to use the raw contacts rather than the plot.

Thanks

**Comment by farhanquadir** [comment]
Hello David,

If you want to use the raw contacts or contact maps, you can download the "deepcomplex_results.tar.gz" at the top "Results of Complex Structure Prediction for Target Name:" section the "Click arrow. " 

After decompresssing it, you can see FILENAME_cmap.txt, FILENAME_rr.txt , FILENAME.rr etc. files. 

We have not yet made the individual contact maps directly downloadable yet. We will keep it mind to incorporate it in our system.

Thanks for your suggestion and please let us know of any other issues.

**Comment by DavidSriker** [comment]
Thanks for your reply!

I wonder, I saw the files, are any of those files contain the intermolecular prediction?
I couldn't see in the readme description what is the composition of the files exported from the server/standalone.

Thanks
